title: Refi Buddy
description: Coming soon…

show_downloads: false
google_analytics: false

optional_front_matter:
  remove_originals: true

readme_index:
  remove_originals: true

titles_from_headings:
  strip_title: false

github:
  is_project_page: false